<script setup lang="ts">
import {
  RefreshLeft,
  RefreshRight,
  DocumentAdd,
  Delete,
  Setting,
  Files,
  CloseBold,
  Camera,
  CopyDocument
} from '@element-plus/icons'
import { Openai, Dialog } from '../openai';
import { ElMessage } from 'element-plus';
import { computed, ref, watch } from 'vue';
import { useMajorStore } from '../store';
import { extractHtmlCodeFromMd, replaceElement } from '../utils';
import { ElMessageBox } from 'element-plus'
import Tips from './tips.vue'
const question = ref<HTMLTextAreaElement | null>(null)
const store = useMajorStore()

const generate = async () => {
  if (store.setting.sk === '') {
    ElMessage({
      message: 'Please set the OpenAI API key first',
      type: 'error',
    })
    return
  }
  if(store.warning) {
    ElMessageBox.confirm(
    'The XSS risk of the code generated by the model is unknown, although measures have been taken to prevent it. Please take security measures before using it. I do not assume any responsibility for any consequences resulting from the use of the generated code. \n模型生成代码xss的风险未知，虽然为您防护了，但请您采取安全措施再使用，本人不承担任何责任。',
    'Disclaimer(免责声明)',
    {
      confirmButtonText: 'OK',
      cancelButtonText: 'Cancel',
      type: 'warning',
    }
  )
    .then(() => {
      store.warning = false
    })
    .catch(() => {
      store.warning = true
    })
    return
  }
  const bridge = new Openai(store.setting.sk, store.setting.model, store.setting.maxTokens);
  if (!question.value) return
  const info = `generate a TailwindCSS code for ${question.value} Webpage.`
  const prompts: Dialog[] = [
    { role: 'system', content: 'As a code generator, your task is to create a code example using TailwindCSS for a specific type of webpage. Your output should be in Markdown format. Please note that the code should not include any image elements.' },
    { role: 'user', content: 'generate a TailwindCSS code for 灰色按钮 Webpage.' },
    { role: 'assistant', content: `\`\`\`htm<button  class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Click me</button>\`\`\`` },
    { role: 'user', content: info }
  ];
  store.controlPanel.freeze = true
  const answer = await bridge.ask(prompts, {
    onMessage: (message: any) => {
      console.log(message)
    }
  })
  store.controlPanel.freeze = false
  const text = extractHtmlCodeFromMd(answer).join("\n");
  store.initHistory(`<div style="width:100vw; height:auto" >${text}</div>`)
  store.controlPanel.action = 'edit'
  ElMessage({
    message: 'generate success',
    type: 'success',
  })
}
const edit = async () => {
  if (store.setting.sk === '') {
    ElMessage({
      message: 'Please set the OpenAI API key first',
      type: 'error',
    })
    return
  }
  if(store.warning) {
    ElMessageBox.confirm(
    'The code generated by the model may have a small probability of XSS risk, although measures have been taken to prevent it. Please take security measures before using it. \n模型生成代码小概率有xss的风险，虽然为您防护了，但请您采取安全措施再使用。',
    'Disclaimer(免责声明)',
    {
      confirmButtonText: 'OK',
      cancelButtonText: 'Cancel',
      type: 'warning',
    }
  )
    .then(() => {
      store.warning = false
    })
    .catch(() => {
      store.warning = true
    })
    return
  }
  const bridge = new Openai(store.setting.sk, store.setting.model, store.setting.maxTokens);
  const info = `Modify blow TailwindCSS code: ${window?.selectedElement?.outerHTML}. Base following requirements: ${question.value}`
  const prompts: Dialog[] = [
    { role: 'system', content: 'As an expert in TailwindCSS, your task is to modify a code snippet according to specific natural language requirements and return the modified code in Markdown format. The code should not include any image elements.' },
    { role: 'user', content: 'Change the text of the button to cancel:<button  class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Click me</button>' },
    { role: 'assistant', content: `\`\`\`htm<button  class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">cancel</button>\`\`\`` },
    { role: 'user', content: info }
  ];
  store.controlPanel.freeze = true
  const answer = await bridge.ask(prompts, {
    onMessage: (message: any) => {
      console.log(message)
    }
  })
  store.controlPanel.freeze = false
  const text = extractHtmlCodeFromMd(answer).join("\n");
  console.log(text, 'text')
  if (window.selectedElement !== null) {
    replaceElement(window.selectedElement, text)
    const code = document.querySelector('#nlu-container')
    store.addHistory(code?.innerHTML || '')
    ElMessage({
      message: 'edit success',
      type: 'success',
    })
  }

}
const placeholder = computed(() => {
  if (store.controlPanel.action === 'edit') {
    return 'Tell me how you would like to edit this component.'
  }
  return 'Input the type of page or component you want to generate and provide a detailed description.'
})

const copy = () => {
  store.copy()
  ElMessage({
    message: 'copy success',
    type: 'success',
  })
}

const github = () => {
  window.open('https://github.com/lxfater/LLMR-NLUP', '_blank')
}
watch(() => store.page, (val) => {
  if (store.page.codes.length === 0) {
    store.controlPanel.action = 'generate'
  }
}, {
  immediate: true,
  deep: true
})
</script>

<template>
  <div class="controlPanelContainer">
    <div class="header">
      <div class="pageAction">
        <el-tooltip class="box-item" effect="dark" content="Add New Page" placement="top">
          <el-icon size="30" @click="store.newPage">
            <DocumentAdd />
          </el-icon>
        </el-tooltip>

        <el-tooltip class="box-item" effect="dark" content="Undo" placement="top">
          <el-icon size="30" @click="store.pre" :disabled="store.page.codesIndex === 0"
            :color="`${store.page.codesIndex === 0 ? 'gray' : 'dark'}`">
            <RefreshLeft />
          </el-icon>
        </el-tooltip>

        <el-tooltip class="box-item" effect="dark" content="Redo" placement="top">
          <el-icon size="30" @click="store.next" :disabled="store.page.codesIndex === store.page.codes.length - 1"
            :color="`${store.page.codesIndex === store.page.codes.length - 1 ? 'gray' : 'dark'}`">
            <RefreshRight />
          </el-icon>
        </el-tooltip>
        <el-tooltip class="box-item" effect="dark" content="Take a screenshot of the current page." placement="top">
          <el-icon size="30" @click="store.screenshot">
            <Camera />
          </el-icon>
        </el-tooltip>
        <el-tooltip class="box-item" effect="dark" content="Copy tailwind css code to clipboard." placement="top">
          <el-icon size="30" @click="copy">
            <CopyDocument />
          </el-icon>
        </el-tooltip>
        <el-tooltip class="box-item" effect="dark" content="Clear current page" placement="top">
          <el-icon size="30" @click="store.clear" color="red">
            <Delete />
          </el-icon>
        </el-tooltip>
      </div>
      <div class="setting">
        <el-tooltip class="box-item" effect="dark" content="Why not star this project on Github?"
          placement="top">
          <el-icon size="30"  color="Blue" @click="github">
            <svg aria-hidden="true" height="24" viewBox="0 0 16 16" version="1.1" width="24" data-view-component="true"
              class="octicon octicon-mark-github">
              <path
                d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z">
              </path>
            </svg>
          </el-icon>
        </el-tooltip>
        <el-tooltip class="box-item" effect="dark" content="Open settings dialog" placement="top">
          <el-icon size="30" @click="store.openSettingDialog">
            <Setting />
          </el-icon>
        </el-tooltip>

        <el-tooltip class="box-item" effect="dark" content="Open file history" placement="top">
          <el-icon size="30" @click="store.openDrawer">
            <Files />
          </el-icon>
        </el-tooltip>

        <el-tooltip class="box-item" effect="dark" content="Fatal bug, used to wipe out everything with file history."
          placement="top">
          <el-icon size="30" @click="store.reset" color="red">
            <CloseBold />
          </el-icon>
        </el-tooltip>
      </div>


    </div>
    <div class="main">
      <el-input v-model="question" :autosize="{ minRows: 5, maxRows: 7 }" type="textarea"
        :placeholder="placeholder"></el-input>
      <div class="action">
        <el-button type="primary" :loading="store.controlPanel.freeze" plain
          v-if="store.controlPanel.action === 'generate'" @Click="generate">generate</el-button>
        <el-button type="primary" :loading="store.controlPanel.freeze" plain v-else @Click="edit">edit</el-button>
      </div>

    </div>
    <div class="footer">
      <Tips />
    </div>
  </div>
</template>
<style lang="scss" scoped>
.controlPanelContainer {
  position: fixed;
  z-index: 1;
  bottom: 0;
  left: calc(50% - 25%);
  width: 50%;
  padding: 10px;
  height: 200px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #fff;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);

  .header {
    height: 40px;
    width: 100%;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 10px;

  }

  .main {
    width: 100%;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;

    .action {
      display: flex;
      width: 200px;
      flex-direction: row;
      justify-content: center;
      align-items: center;
    }

    .el-input {
      width: 200px;
      flex: 1;
      height: 100%;
      border-radius: 8px;
      border-color: #e1e1e1;
      box-shadow: none;

      &:focus {
        border-color: #0099ff;
        box-shadow: 0 0 4px rgba(0, 153, 255, 0.5);
      }

      &::placeholder {
        color: #c4c4c4;
      }
    }

    .el-button {
      width: 100px;
      flex: 0;
      width: 120px;
      height: 48px;
      margin-left: 20px;
      border-radius: 4px;
      background-color: #0099ff;
      color: #fff;

      &:hover {
        background-color: darken(#0099ff, 10%);
      }
    }
  }

  .footer {
    height: 80px;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
  }
}</style>
